services:
  postgres:
    image: postgres
    container_name: auctions-db
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auctions
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: search-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
    - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata: